"""Guidance cost reporter — the recurring tokens-read-per-session tax (D1).

``python -m ai_router.guidance_report`` measures the always-loaded
guidance files (``lessons-learned.md``, ``project-guidance.md``) and
reports, per file and combined, their bytes / lines / estimated tokens.
The metric is framed as **tokens-read-per-session** — what every session
start pays to load these files into context — not disk KB and not a
billing number.

Modes
-----

- default: read-only report (never dirties tracked docs).
- ``--check``: exit non-zero if any capped file is over its ceiling (an
  opt-in hard CI gate). Mirrors the Set 053 drift-guard ``--check``.
- ``--write-headers``: stamp a single freshness marker block into each
  capped file (opt-in, the only mode that writes). Re-running replaces
  the existing block in place rather than appending.

Ceilings are enforced **per active file** (the D5 ``lessons-learned`` and
``project-guidance`` values from the router-config ``guidance:`` block);
the archive is uncapped and the combined total is informational only.

ASCII-only output (Windows cp1252 consoles).
"""

from __future__ import annotations

import argparse
import datetime
import os
import sys
from dataclasses import dataclass
from typing import List, Optional

try:  # test convention: bare import; production: relative fallback
    from config import load_config  # type: ignore[import-not-found]
    from guidance_config import (  # type: ignore[import-not-found]
        LESSONS_ACTIVE,
        PROJECT_GUIDANCE,
        GuidanceConfig,
        discover_guidance_files,
        estimate_tokens,
        load_guidance_config,
    )
except ImportError:
    from .config import load_config  # type: ignore[no-redef]
    from .guidance_config import (  # type: ignore[no-redef]
        LESSONS_ACTIVE,
        PROJECT_GUIDANCE,
        GuidanceConfig,
        discover_guidance_files,
        estimate_tokens,
        load_guidance_config,
    )


# Freshness-header marker block (single stable placement: just before the
# first horizontal rule under the purpose preamble). Re-running
# --write-headers replaces everything between these two lines.
HEADER_BEGIN = "<!-- guidance-overhead: AUTO-GENERATED by ai_router.guidance_report; do not edit by hand"
HEADER_END = "-->"


@dataclass
class FileReport:
    name: str
    path: str
    bytes: int
    lines: int
    tokens: int
    ceiling: Optional[int]  # None = uncapped

    @property
    def over_ceiling(self) -> bool:
        return self.ceiling is not None and self.tokens > self.ceiling

    @property
    def pct_of_ceiling(self) -> Optional[int]:
        if self.ceiling is None or self.ceiling == 0:
            return None
        return round(100 * self.tokens / self.ceiling)


def measure_file(name: str, path: str, cfg: GuidanceConfig) -> FileReport:
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    return FileReport(
        name=name,
        path=path,
        bytes=len(text.encode("utf-8")),
        lines=text.count("\n") + (0 if text.endswith("\n") or text == "" else 1),
        tokens=estimate_tokens(text),
        ceiling=cfg.ceiling_for(name),
    )


def build_reports(
    repo_root: Optional[str], cfg: GuidanceConfig
) -> List[FileReport]:
    """Measure the always-loaded files that exist (the two capped files).

    The archive is excluded — it is never auto-loaded, so it is not part
    of the recurring tax this reporter exists to surface.
    """
    found = discover_guidance_files(repo_root)
    reports: List[FileReport] = []
    for name in (LESSONS_ACTIVE, PROJECT_GUIDANCE):
        if name in found:
            reports.append(measure_file(name, found[name], cfg))
    return reports


def _fmt(n: int) -> str:
    return f"{n:,}"


def _status_token(r: FileReport) -> str:
    if r.ceiling is None:
        return "uncapped"
    if r.over_ceiling:
        return f"OVER by {_fmt(r.tokens - r.ceiling)} tokens"
    return f"OK ({r.pct_of_ceiling}% of ceiling)"


def render_report(reports: List[FileReport]) -> str:
    lines: List[str] = []
    lines.append("Guidance overhead (tokens-read-per-session):")
    if not reports:
        lines.append("  (no guidance files found under docs/planning)")
        return "\n".join(lines)
    total_bytes = total_lines = total_tokens = 0
    for r in reports:
        total_bytes += r.bytes
        total_lines += r.lines
        total_tokens += r.tokens
        ceil_txt = "uncapped" if r.ceiling is None else f"ceiling {_fmt(r.ceiling)}"
        lines.append(
            f"  {r.name:<22} {_fmt(r.bytes):>9} bytes  {_fmt(r.lines):>5} lines  "
            f"~{_fmt(r.tokens):>7} tokens  [{ceil_txt}: {_status_token(r)}]"
        )
    lines.append(
        f"  {'COMBINED':<22} {_fmt(total_bytes):>9} bytes  {_fmt(total_lines):>5} lines  "
        f"~{_fmt(total_tokens):>7} tokens  [informational only]"
    )
    return "\n".join(lines)


def _build_header_block(
    r: FileReport, last_pruned_set: str, today: str
) -> str:
    ceil_txt = "uncapped" if r.ceiling is None else f"{_fmt(r.ceiling)} tokens"
    return "\n".join(
        [
            HEADER_BEGIN,
            f"size: {_fmt(r.bytes)} bytes / {_fmt(r.lines)} lines / ~{_fmt(r.tokens)} tokens",
            f"ceiling: {ceil_txt}   status: {_status_token(r)}",
            f"last-pruned-set: {last_pruned_set}   generated: {today}",
            HEADER_END,
        ]
    )


def _existing_last_pruned(text: str) -> Optional[str]:
    """Recover the last-pruned-set value from an existing header, if any."""
    for line in text.split("\n"):
        s = line.strip()
        if s.startswith("last-pruned-set:"):
            # "last-pruned-set: 064   generated: ..."
            rest = s[len("last-pruned-set:"):].strip()
            return rest.split("   ")[0].strip() or None
    return None


def stamp_header(text: str, block: str) -> str:
    """Insert or replace the freshness header block in *text*.

    If a marker block already exists, replace it in place. Otherwise
    insert the block just before the first ``---`` horizontal rule (which
    sits below the purpose preamble in both files); if there is no rule,
    insert after the first blank line.
    """
    lines = text.split("\n")
    # Locate an existing block.
    begin_idx = end_idx = None
    for i, line in enumerate(lines):
        if line.strip() == HEADER_BEGIN:
            begin_idx = i
        elif begin_idx is not None and line.strip() == HEADER_END:
            end_idx = i
            break
    block_lines = block.split("\n")
    if begin_idx is not None and end_idx is not None:
        lines[begin_idx : end_idx + 1] = block_lines
        return "\n".join(lines)
    # Insert before the first horizontal rule.
    insert_at = None
    for i, line in enumerate(lines):
        if line.strip() == "---":
            insert_at = i
            break
    if insert_at is None:
        for i, line in enumerate(lines):
            if line.strip() == "":
                insert_at = i + 1
                break
    if insert_at is None:
        insert_at = len(lines)
    new_block = block_lines + [""]
    lines[insert_at:insert_at] = new_block
    return "\n".join(lines)


def summarize_overhead(repo_root: Optional[str] = None) -> Optional[str]:
    """Return a terse ASCII over-ceiling advisory for the lifecycle CLIs, or None.

    Set 064 D5 backstop seam (non-blocking, mirrors the Set 053 drift
    advisory in :func:`check_migrations.summarize_drift`): chained into
    ``start_session`` / ``close_session`` so a guidance file that has
    grown past its token ceiling surfaces a soft note at the session
    boundary — for every orchestrator on every host, with no CI job or
    git hook required. **Fail-open**: any error returns ``None`` (silent);
    a measurement failure must never disrupt a session boundary. The
    ceiling is a *backstop* — the line says "a sweep is due", it never
    blocks or migrates.
    """
    try:
        try:
            config = load_config()
        except Exception:
            config = None
        cfg = load_guidance_config(config)
        reports = build_reports(repo_root, cfg)
    except Exception:
        return None
    over = [r for r in reports if r.over_ceiling]
    if not over:
        return None
    parts = ", ".join(
        f"{r.name} ~{_fmt(r.tokens)} tok (ceiling {_fmt(r.ceiling or 0)})" for r in over
    )
    return (
        f"[dabbler] {len(over)} guidance file(s) over the token ceiling: {parts}. "
        "A pruning sweep is due before adding new content (archive by the "
        "evidence rules, not raw length). Backstop only -- not blocking."
    )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ai_router.guidance_report",
        description=(
            "Report the recurring tokens-read-per-session overhead of the "
            "always-loaded guidance files. Read-only by default. --check "
            "exits non-zero when a capped file is over its ceiling; "
            "--write-headers stamps a freshness block into each capped file."
        ),
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help="Repo root containing docs/planning (default: current directory).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any capped file is over its token ceiling.",
    )
    parser.add_argument(
        "--write-headers",
        action="store_true",
        help="Stamp/refresh the freshness header block in each capped file.",
    )
    parser.add_argument(
        "--last-pruned-set",
        default=None,
        help=(
            "Value to record as last-pruned-set in stamped headers. Default: "
            "preserve the existing header's value, or '(none)'."
        ),
    )
    parser.add_argument(
        "--json", action="store_true", help="Machine-readable JSON output."
    )
    args = parser.parse_args(argv)

    try:
        config = load_config()
    except Exception:
        config = None
    cfg = load_guidance_config(config)
    reports = build_reports(args.repo_root, cfg)

    if args.json:
        import json

        print(
            json.dumps(
                {
                    "files": [
                        {
                            "name": r.name,
                            "bytes": r.bytes,
                            "lines": r.lines,
                            "tokens": r.tokens,
                            "ceiling": r.ceiling,
                            "over_ceiling": r.over_ceiling,
                            "pct_of_ceiling": r.pct_of_ceiling,
                        }
                        for r in reports
                    ],
                },
                indent=2,
            )
        )
    else:
        print(render_report(reports))

    if args.write_headers:
        today = datetime.date.today().isoformat()
        for r in reports:
            with open(r.path, "r", encoding="utf-8") as f:
                text = f.read()
            lp = args.last_pruned_set or _existing_last_pruned(text) or "(none)"
            block = _build_header_block(r, lp, today)
            new_text = stamp_header(text, block)
            if new_text != text:
                with open(r.path, "w", encoding="utf-8", newline="") as f:
                    f.write(new_text)
                print(f"  stamped header into {r.name}")

    if args.check:
        over = [r for r in reports if r.over_ceiling]
        if over:
            names = ", ".join(f"{r.name} (+{r.tokens - (r.ceiling or 0)} tok)" for r in over)
            print(
                f"CHECK FAILED: {len(over)} guidance file(s) over ceiling: {names}. "
                "Run a pruning sweep (see docs/planning archive triggers) before adding."
            )
            return 1

    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())


__all__ = [
    "HEADER_BEGIN",
    "HEADER_END",
    "FileReport",
    "measure_file",
    "build_reports",
    "render_report",
    "stamp_header",
    "summarize_overhead",
    "main",
]
